### ISSUE TITLE
`template.yml` - invalud value `number` and other oopsies

### ISSUE THREAD

**Issue by sneakers-the-rat** [myst-templates/book-theme#3]
hello hello :)

when using myst and the default `myst.yml` config that pulls this theme, i am getting:

```
🌎 Cloning template from https://github.com/myst-templates/book-theme.git
💾 Saved template to path _build/templates/site/myst/book-theme
'options.3' extra keys ignored: min, max, integer (at _build/templates/site/myst/book-theme/template.yml#template)
'type' invalid value 'number' - must be one of [boolean, string, choice, file] (at _build/templates/site/myst/book-theme/template.yml#template.options.3)
'files.3' file does not exist: _build/templates/site/myst/book-theme/public/**/* (at _build/templates/site/myst/book-theme/template.yml#template)
'files.4' file does not exist: _build/templates/site/myst/book-theme/build/**/* (at _build/templates/site/myst/book-theme/template.yml#template)
Cannot use invalid template.yml: _build/templates/site/myst/book-theme/template.yml

Myst CLI Versions:
 - node                         21.7.1     Required: >= 14.0.0      ✅
 - npm                          10.5.0     Required: >=7            ✅
 - myst                         0.1.11
```

It looks like https://github.com/myst-templates/book-theme/blame/581a880565428ee652745f90bdd885c8c5a48efe/template.yml#L25 was changed 5 months ago, so there must be something wrong with my validator version, since presumably this would have popped up before now otherwise. 

the files markes as not existing definitely do exist, so not sure what that's about.

Sorry I can't be more descriptive with an issue here, and not sure if this goes here or in myst repo

**Comment by rowanc1** [comment]
It looks like your myst version is out of date (0.1.11), can you update to the latest (v1.1.55) and see if the error persists?

**Comment by sneakers-the-rat** [comment]
ok yes this was confusing -- i just figured this out. I had installed mystmd from pip as part of a python project, but that didn't seem to set the entrypoint in the venv, but i force-reinstalled the pip package again and then it did??? my mistake!!!

**Comment by rowanc1** [comment]
Glad you are back up and running, very early version of mystmd you had. :)
